### ISSUE TITLE
WL14c

### ISSUE THREAD

**Issue by RobWoods-CPG** [drooger/WebLogic_Automation#1]
I am starting to look at this process for weblogic 14c on windows.  Do you have anything in place for 14c?  if not I would like to start working on it.  Is it OK to take your code here and update it for 14c, and windows?

**Comment by weblogicwlst** [comment]
take a look at this https://wlatricksntips.blogspot.com/2017/03/single-click-installation-of-weblogic.html

**Comment by RobWoods-CPG** [comment]
Thanks.  I'm looking more for the Patching process, and we do want to move most of our deployment to Ansible.  Be it with ansible yaml, or powershell scripting.
